### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by suravijayjilla** [eichsfeld/autocrop#1]
I am getting error in this line.
for f in files[0]:

IndexError: list index out of range

**Comment by eichsfeld** [comment]
Hey.

Are you sure you placed autocrop.py in a folder that contains at least one image file?
(Files should have extensions like: .jpg, .jpeg, .png,...)

Please make sure to pull the repository again, I just made some important changes. (unrelated to your issue though)

**Comment by suravijayjilla** [comment]
Thanks for your valuable reply.
Now its working.

You have any logic to crop the particular content from the image automatically using python.
